# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.77364405, 0.87196049, 0.59808728],
       [0.29353354, 0.10393332, 0.28942597],
       [0.28961742, 0.04730743, 0.96015552],
       [0.32570184, 0.96574236, 0.98904743],
       [0.05292151, 0.58943251, 0.68877895],
       [0.22502113, 0.41957581, 0.67797525],
       [0.35137135, 0.34641843, 0.52325857],
       [0.30352432, 0.08681051, 0.25672226],
       [0.20242592, 0.73100997, 0.67008457],
       [0.79225083, 0.95256206, 0.52399524],
       [0.2545336 , 0.54981461, 0.01137414],
       [0.80114147, 0.57686426, 0.88871256],
       [0.30947217, 0.7650581 , 0.19836746],
       [0.0593685 , 0.42230059, 0.74674431],
       [0.01489533, 0.89417102, 0.43945091],
       [0.10312596, 0.3480241 , 0.40401502],
       [0.9802576 , 0.25282712, 0.08761001],
       [0.51922567, 0.68911353, 0.03413567],
       [0.74501249, 0.27496087, 0.41658904],
       [0.26014883, 0.45776911, 0.33353587],
       [0.85588265, 0.31627129, 0.46467753],
       [0.1260018 , 0.54923214, 0.84172246],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.05292151, 0.58943251, 0.68877895],
       [0.01489533, 0.89417102, 0.43945091]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0]),
 array([0.77547303, 0.67311694, 0.65082241, 0.55333477, 0.        ,
        0.24204607, 0.41895721, 0.70859271, 0.20674918, 0.78411659,
        0.59938099, 0.77457376, 0.40195384, 0.17701589, 0.        ,
        0.37668157, 1.15527465, 0.67873273, 0.80744639, 0.43182873,
        0.87725999, 0.17420826, 0.57015229, 0.73941841, 0.84200025,
        0.67507387, 0.44526801, 0.5087625 , 0.64893647, 0.29684476]))

In [6]:
labels = clusters[0]
labels

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0])

In [8]:
!pip install chart_studio
import chart_studio.plotly as py
import plotly.graph_objects as go 
import plotly.graph_objects as go
import plotly.offline as ply

  Using cached chart_studio-1.1.0-py3-none-any.whl (64 kB)
  Using cached retrying-1.3.3.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     --------------------------------------- 27.7/27.7 MB 19.3 MB/s eta 0:00:00
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11448 sha256=e9ce14ea3665b334b81fd5d63d8d807f88436733ee8e43614c85187e0c1645a8
  Stored in directory: c:\users\alberto\appdata\local\pip\cache\wheels\ce\18\7f\e9527e3e66db1456194ac7f61eb3211068c409edceecff2d31
Successfully built retrying


In [9]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters.html')

'Clusters.html'

In [10]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers)

(array([[0.38828256, 0.38472954, 0.57417378],
        [0.46252748, 0.8103689 , 0.27423132]]),
 0.400601972705352)

In [12]:
kmeans(data, 2)

(array([[0.54471525, 0.45158408, 0.34829502],
        [0.19694308, 0.53273736, 0.7380255 ]]),
 0.37718599675048464)