# Regresión lineal Python
* El paquete scikit-learn para regresion lineal y seleccion de rasgos

In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/ads/Advertising.csv")
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
colsX = ["TV", "Radio", "Newspaper"] #Columnas de prediccion

In [8]:
X = data[colsX]
Y = data["Sales"]

In [11]:
#Queremos estimar un modelo lineal
estimator = SVR(kernel="linear")

#RFE(estimador, numeroDeseadoDeVariables, pasos)
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X, Y)

In [12]:
selector.support_

array([ True,  True, False])

###### Array que nos indica que variables son seleccionadas (de colsX) para entrenar el modelo.
###### En nuestro caso seran TV y Radio dado que Newspaper esta a false.

In [13]:
selector.ranking_

array([1, 1, 2])

###### Las variables seleccionadas siempren aparecen con rango 1, de ahi el resto aparecen con otros números rango 2 mas significativa que rango 3, 4, 5...

In [14]:
from sklearn.linear_model import LinearRegression

In [16]:
X_pred = X[["TV","Radio"]]

In [17]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [18]:
lm.intercept_ #Donde corta el eje. (alfa)

2.9210999124051362

In [19]:
lm.coef_ #Coeficientes

array([0.04575482, 0.18799423])

In [20]:
lm.score(X_pred, Y) #Valor de r^2

0.8971942610828956